---
kind: pipeline
name: python-template

steps:
  - name: lint python files
    image: udcservice/python:3.7
    commands:
      - make init
      - make lint

  - name: test python functions
    image: udcservice/python:3.7
    commands:
      - make init
      - make test

  - name: create ECR Repo
    image: hashicorp/terraform:latest
    commands:
      - make init-ecr

  - name: publish Docker image
    image: plugins/ecr
    settings:
      repo: udc/python-template
      registry: 613868415919.dkr.ecr.us-east-1.amazonaws.com
      region: us-east-2
      tags:
        - 1.0
    when:
      branch:
      - master